# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2EwYjUwYTllMjQyYzhiMzdkOGQxYzU2MWJlNWJkYjRiMmFmNTcyNmQzZThjNzkxMjMwMjI1MTgyOGY0ZTE3YmE3ZjRhODBmNjdjZTcxMzVmNTJhYTU3NTQ4MmExZjdmZDUzNzE3MDVkYmVkMmMwOTU1MjczMDEzZjk4ZDE4ZTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
